name: PHP Composer with Cache
author: Sam Anthony

inputs:
  GITHUB_TOKEN:
    description: Pass in the GITHUB_TOKEN
    required: true
  deployment_environment:
    description: The GitHub Deployment environment
    required: true

runs:
  using: "composite"
  steps:
    - uses: octokit/graphql-action@v2.x
      id: api-request
      with:
        query: |
          query ($repo_owner: String!, $repo_name: String!,  $deployment_environment: String!) {
            repository(owner: $repo_owner, name: $repo_name) {
              deployments(orderBy: {field: CREATED_AT, direction: DESC}, first: 100, environments: [$deployment_environment]) {
                nodes {
                  description,
                  createdAt,
                  environment,
                  latestEnvironment,
                  latestStatus {
                    description,
                    state
                  }
                  ref {
                    name,
                    prefix
                  }
                }
              }
            }
          }
        variables: |
          repo_owner: "${{ github.event.repository.owner.name }}"
          repo_name: "${{ github.event.repository.name }}"
          deployment_environment: "${{ inputs.deployment_environment }}"
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: My Name
      shell: bash
      run: |
        echo '${{ steps.api-request.outputs.data }}'
        echo '${{ steps.api-request.outputs.data }}' | jq '[ .repository.deployments.nodes[] | select(.latestStatus.state == "FAILURE" ) ] | limit(1;.[]) | {deployment_created_at: .createdAt, deployment_ref_name: .ref.name}'
        # TODO - and .ref.prefix == "refs/tags/"