name: PHP Composer with Cache
author: Sam Anthony

inputs:
  GITHUB_TOKEN:
    description: Pass in the GITHUB_TOKEN
    required: true

runs:
  using: "composite"
  steps:
    - uses: octokit/graphql-action@v2.x
      id: api-request
      with:
        query: |
          query ($repo_owner: String!, $repo_name: String!) {
            repository(owner: $repo_owner, name: $repo_name) {
              deployments(orderBy: {field: CREATED_AT, direction: DESC}, first: 100, environments: ["test"]) {
                nodes {
                  description,
                  createdAt,
                  environment,
                  latestEnvironment,
                  latestStatus {
                    description,
                    state
                  }
                  ref {
                    name,
                    prefix
                  }
                }
              }
            }
          }
        variables: |
          repo_owner: "${{ github.event.repository.owner.name }}"
          repo_name: "${{ github.event.repository.name }}"
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: My Name
      shell: bash
      run: |
        echo '${{ steps.api-request.outputs.data }}'