name: PHP Composer with Cache
author: Sam Anthony


# GITHUB_REPOSITORY

runs:
  using: "composite"
  steps:
    - uses: octokit/graphql-action@v2.x
      id: api-request
      with:
        query: |
          query {
            viewer {
              name
            }
          }
        owner: ${{ github.event.repository.owner.name }}
        repo: ${{ github.event.repository.name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: "echo '${{ steps.api-request.outputs.data }}'"