name: PHP Composer with Cache
author: Sam Anthony

inputs:
  GITHUB_TOKEN:
    description: Pass in the GITHUB_TOKEN
    required: true

runs:
  using: "composite"
  steps:
    - uses: octokit/graphql-action@v2.x
      id: api-request
      with:
        query: |
          query {
            viewer {
              name
            }
          }
        owner: ${{ github.event.repository.owner.name }}
        repo: ${{ github.event.repository.name }}
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: My Name
      shell: bash
      run: |
        echo '${{ steps.api-request.outputs.data }}'