name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: test
    name: Automated test action
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        uses: the-pistol/github-action-read-deployments@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
